version: "3.8"

services:
  frontend:
    image: mercari-build-training/web:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:9000
    depends_on:
      - api

  api:
    image: mercari-build-training/app:latest
    user: root
    ports:
      - "9000:9000"
    volumes:
      - ./python/items.json:/app/items.json
    environment:
      - FRONT_URL=http://localhost:3000